name: MaSuiteWarps
main: fi.matiaspaavilainen.masuitewarps.bukkit.MaSuiteWarps
version: ${project.version}
author: Masagameplay
depends: [MaSuiteCore]
api-version: 1.13
commands:
  warp:
    description: Warps player to specified location
    aliases: [warpto, tt]
    permission: masuitewarps.warp
  setwarp:
    description: Creates warp point
    aliases: [warpset, createwarp]
    permission: masuitewarps.setwarp
  delwarp:
    description: Deletes warp point
    aliases: [warpdel, deletewarp]
    permission: masuitewarps.delwarp
  warps:
    description: Lists all available warps
    aliases: [listwarps, warplist, tts]