name: MaSuiteWarps
main: dev.masa.masuitewarps.bukkit.MaSuiteWarps
version: ${project.version}
author: Masagameplay
depends: [MaSuiteCore]
softdepend: [Multiverse, Multiworld, Essentials]
loadbefore: [Essentials]
api-version: '1.15'